##Numpy

In [1]:
import numpy as np

List Vs Numpy time taken

In [2]:
from time import process_time

Time taken by list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0008405279999994519


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.00021258800000012457


##Numpy Arrays

In [6]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating 1D Array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
a.shape

(5,)

In [11]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [13]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays


In [14]:
#Creating a numpy array of zeroes
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#creating  numpy array of 1
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#array of particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
#creating identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.27116505 0.81453072 0.53843536 0.81317348]
 [0.71909198 0.164703   0.30182025 0.01730445]
 [0.85664726 0.2812938  0.31111293 0.13507203]]


In [19]:
#random integer values
c=np.random.randint(10,100,(3,5))
print(c)

[[89 99 41 94 24]
 [58 89 55 72 59]
 [85 19 19 32 99]]


In [20]:
#array of evenly spced value
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [22]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [23]:
#Convert a list to numpy array
list2=[10,20,20,20,50]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

##Analysing Numpy Array


In [24]:
c=np.random.randint(10,90,(5,5))
print(c)

[[21 70 73 29 77]
 [66 18 50 43 46]
 [24 53 42 83 46]
 [68 64 32 83 69]
 [10 66 42 14 71]]


In [25]:
#Array dim
print(c.shape)

(5, 5)


In [27]:
#number of dim
print(c.ndim)


2


In [28]:
#NUMBER OF ELEMENTS IN THE ARRAY
print(c.size)

25


In [29]:
#checking of datatype values in array
print(c.dtype)

int64


##MATHEMATICAL OPERATIONS

In [30]:
list1=[1,2,3,4]
list2=[5,6,7,8]

print(list1+list2)  #concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8]


In [32]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[9 8 9]
 [2 5 2]
 [1 4 8]]
[[12 11 14]
 [10 18 12]
 [15 17 11]]


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 19 23]
 [12 23 14]
 [16 21 19]]
[[ -3  -3  -5]
 [ -8 -13 -10]
 [-14 -13  -3]]
[[108  88 126]
 [ 20  90  24]
 [ 15  68  88]]
[[0.75       0.72727273 0.64285714]
 [0.2        0.27777778 0.16666667]
 [0.06666667 0.23529412 0.72727273]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 19 23]
 [12 23 14]
 [16 21 19]]
[[ -3  -3  -5]
 [ -8 -13 -10]
 [-14 -13  -3]]
[[108  88 126]
 [ 20  90  24]
 [ 15  68  88]]
[[0.75       0.72727273 0.64285714]
 [0.2        0.27777778 0.16666667]
 [0.06666667 0.23529412 0.72727273]]


##Array Manipulation


In [36]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 8 3]
 [2 8 1]]
(2, 3)


In [38]:
#Tarnspose
transpose=np.transpose(array)
print(transpose)
print(transpose.shape)

[[6 2]
 [8 8]
 [3 1]]
(3, 2)


In [39]:
#Another method
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 8 7]
 [5 2 9]]
(2, 3)


In [40]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[1 5]
 [8 2]
 [7 9]]
(3, 2)


In [41]:
#Reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[7 9 4]
 [4 3 1]]
(2, 3)


In [43]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[7 9]
 [4 4]
 [3 1]]
(3, 2)
